name: CI - Docker Flask App1

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    - name:  Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name:  Install dependencies
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name:  Test Flask App
      run: |
        cd app
        python app.py &   # Start app in background
        sleep 5
        curl http://localhost:5000

    - name:  Build Docker Image (locally on runner for testing)
      run: |
        cd app
        docker build -t devops-demo-app .

    - name:  Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Install Git (one-time setup)
          sudo yum install git -y
          # Clean up old container and app if any
          docker stop demo || true
          docker rm demo || true
          rm -rf app || true

          # Clone your repo
          git clone https://github.com/fatimabolotbek/DockerCompose-demo.git appleboy
          cd app/app

          # Build and run Docker app on EC2
          docker build -t devops-demo-app .
          docker run -d -p 5050:5000 --name demo devops-demo-app
